name: with_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1 #https://pub.dev/packages/firebase_auth
  provider: ^4.3.2+1
  get_it: ^4.0.4 #https://pub.dev/packages/get_it
  flutter_svg: ^0.18.1
  email_validator: ^1.0.5
  firebase_dynamic_links: ^0.6.0
  google_fonts: ^1.1.0
  flutter_holo_date_picker: ^0.2.0 #https://pub.dev/packages/flutter_holo_date_picker
  url_launcher: ^5.5.1
  firebase_storage: ^4.0.0 #https://pub.dev/packages/firebase_storage
  flushbar: ^1.10.4 #https://pub.dev/packages/flushbar
  sleek_circular_slider: ^1.1.0 #https://pub.dev/packages/sleek_circular_slider
  timeago: ^2.0.27 #https://pub.dev/packages/timeago
  flutter_facebook_login: ^3.0.0 #https://pub.dev/packages/flutter_facebook_login
  google_sign_in: ^4.5.3 #https://pub.dev/packages/google_sign_in
  skeleton_loader: ^1.0.2+1 #https://pub.dev/packages/skeleton_loader
  tinycolor: ^1.0.3 #https://pub.dev/packages/tinycolor
  functional_widget_annotation: ^0.8.0 #https://pub.dev/packages/functional_widget_annotation
  flutter_multi_formatter: ^1.1.6 #https://pub.dev/packages/flutter_multi_formatter
  flutter_fadein: ^1.1.1 #https://pub.dev/packages/flutter_fadein
  no_context_navigation: ^1.0.3 #https://pub.dev/packages/no_context_navigation
  share: ^0.6.5+1 #https://pub.dev/packages/share
  floating_pullup_card: ^0.2.2 #https://pub.dev/packages/floating_pullup_card
  easy_debounce: ^1.0.2 #https://pub.dev/packages/easy_debounce
  keyboard_utils: ^1.2.4 #https://pub.dev/packages/keyboard_utils
  after_layout: ^1.0.7+2 #https://pub.dev/packages/after_layout
  image_picker: ^0.6.7+12 #https://pub.dev/packages/image_picker
  camera: ^0.5.8+9 #https://pub.dev/packages/camera
  native_device_orientation: ^0.4.3 #https://pub.dev/packages/native_device_orientation
  video_player: ^0.11.1+2 #https://pub.dev/packages/video_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5 #https://pub.dev/packages/flutter_launcher_icons
  flutter_driver:
    sdk: flutter
  test: any

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'images/launcher.png'
  adaptive_icon_background: 'images/adaptive_icon_background.png'
  adaptive_icon_foreground: 'images/adaptive_icon_foreground.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/launcher.png
    - images/logo_light.svg
    - images/selfie.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: With
      fonts:
        - asset: fonts/With.ttf
