/// Flutter icons With
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  With
///      fonts:
///       - asset: fonts/With.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class With {
  With._();

  static const _kFontFam = 'With';
  static const _kFontPkg = null;

  static const IconData lock_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_settings_new = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gavel = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fairy_wand = IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xf128, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xf359, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf39e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
